---

# create disable ipv6 file

- name: create file
  template: src=sysctl.conf dest=/etc/sysctl.conf owner=root group=bin mode=0644

- name: apply sysctl
  shell: sysctl -p

- name: system reboot
  shell: /sbin/reboot

- name: wait for the server to go down (reboot)
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped

- name: wait for the server to come up
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=60 timeout=120 state=started


