---

- name: exist wheezy-backports
  stat: path=/etc/apt/sources.list.d/wheezy-backports.list
  register: filepath

- name: add wheezy-backports
  shell: sh -c "echo deb http://http.debian.net/debian wheezy-backports main > /etc/apt/sources.list.d/wheezy-backports.list"

- name: update apt
  apt: upgrade=full update_cache=yes




